### ISSUE TITLE
[BUG] Github integration hangs on Github.[get]Username

### ISSUE THREAD

**Issue by jared252016** [linuxserver/docker-dillinger#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/joemccann/dillinger/blob/master/plugins/github/README.md

While setting this up, the application hangs presumably after the request for the access_token at the part where it runs Github.getUsername

### Expected Behavior

Should return to Dillinger and recognize that Github was connected.

### Steps To Reproduce

1. Docker-Compose / Docker on Ubuntu 22.04
2. 
```
version: "2.1"
services:
  dillinger:
    image: lscr.io/linuxserver/dillinger:latest
    container_name: dillinger
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - github_client_id=ID
      - github_client_secret=SECRET
      - github_callback_url=https://dmydomain/oauth/github
      - github_redirect_uri=https://mydomain/
    volumes:
      - ./config:/config
    ports:
      - 9021:8080
    restart: unless-stopped
    security_opt:
      - seccomp=./pdf-export.json
```
3. docker-compose up -d and navigate to website and link Github
4. Request times out at reverse proxy, indicating issue with Dillinger. Last console log was about the username.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed:
sudo apt install docker.io docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
dillinger    | [migrations] started
dillinger    | [migrations] no migrations found
dillinger    | usermod: no changes
dillinger    | ───────────────────────────────────────
dillinger    |
dillinger    |       ██╗     ███████╗██╗ ██████╗
dillinger    |       ██║     ██╔════╝██║██╔═══██╗
dillinger    |       ██║     ███████╗██║██║   ██║
dillinger    |       ██║     ╚════██║██║██║   ██║
dillinger    |       ███████╗███████║██║╚██████╔╝
dillinger    |       ╚══════╝╚══════╝╚═╝ ╚═════╝
dillinger    |
dillinger    |    Brought to you by linuxserver.io
dillinger    | ───────────────────────────────────────
dillinger    |
dillinger    | To support LSIO projects visit:
dillinger    | https://www.linuxserver.io/donate/
dillinger    |
dillinger    | ───────────────────────────────────────
dillinger    | GID/UID
dillinger    | ───────────────────────────────────────
dillinger    |
dillinger    | User UID:    1000
dillinger    | User GID:    1000
dillinger    | ───────────────────────────────────────
dillinger    |
dillinger    | [custom-init] No custom files found, skipping...
dillinger    | Dropbox config not found at /app/dillinger/configs/dropbox/dropbox-config.json. Plugin disabled.
dillinger    | Bitbucket config not found at /app/dillinger/configs/bitbucket/bitbucket-config.json. Plugin disabled.
dillinger    | Github config found in environment. Plugin enabled. (Key: "2691dda8b9d282e3d332")
dillinger    | Medium config not found at /app/dillinger/configs/medium/medium-config.json. Plugin disabled.
dillinger    | Google Drive config not found at /app/dillinger/configs/googledrive/googledrive-config.json. Plugin disabled.
dillinger    | OneDrive config not found at /app/dillinger/configs/onedrive/onedrive-config.json. Plugin disabled.
dillinger    | Sponsored config not found at /app/dillinger/configs/sponsored/sponsored-config.json. Plugin disabled.
dillinger    | GoogleAnalytics config not found at /app/dillinger/configs/googleanalytics/googleanalytics-config.json. Plugin disabled.
dillinger    | Express server listening on port 8080
dillinger    |
dillinger    | http://localhost:8080
dillinger    |
dillinger    | [ls.io-init] done.
dillinger    | 192.168.1.1 - GET / HTTP/1.1 200 - - 107.214 ms
dillinger    | 192.168.1.1 - GET /assets/app-9a52b028cbd397404e2c56df7c2f8e87.css HTTP/1.1 200 72955 - 2.438 ms
dillinger    | 192.168.1.1 - GET /img/icons/file.svg HTTP/1.1 200 - - 7.041 ms
dillinger    | 192.168.1.1 - GET /js/main.bundle.js HTTP/1.1 200 - - 12.310 ms
dillinger    | 192.168.1.1 - GET /theme-github.js HTTP/1.1 404 154 - 17.537 ms
dillinger    | 192.168.1.1 - GET /img/icons/enter-zen.svg HTTP/1.1 200 - - 1.229 ms
dillinger    | 192.168.1.1 - GET /img/icons/code.svg HTTP/1.1 200 902 - 1.206 ms
dillinger    | 192.168.1.1 - GET /redirect/github?scope=public_repo HTTP/1.1 302 364 - 5.832 ms
dillinger    | about
dillinger    | getting username from github
```
